# Schema for the configuration files of the Display Suite module.

ds.settings:
  type: mapping
  label: 'Display Suite settings'
  mapping:
    disabled:
      type: boolean
      label: 'Disable Display Suite attaching fields'
    field_template:
      type: boolean
      label: 'Uses field templates'
    ft-default:
      type: string
      label: 'The default template'
    ft-show-colon:
      type: boolean
      label: 'Kill the label colon'
    classes:
      type: mapping
      label: 'Display Suite classes'
      mapping:
        region:
          type: sequence
          label: 'Region classes'
          sequence:
            - type: string
              label: 'Region class'
        field:
          type: sequence
          label: 'Field classes'
          sequence:
            - type: string
              label: 'Field class'

entity_view_display.third_party.ds:
  type: mapping
  label: 'Entity View Display Suite settings'
  mapping:
    layout:
      type: mapping
      label: 'The Display Suite layout'
      mapping:
        id:
          type: string
          label: 'The id of the layout'
        path:
          type: string
          label: 'The path of the module'
        css:
          type: string
          label: 'The path to the css file'
        settings:
          type: mapping
          label: 'Display Suite layout settings'
          mapping:
            classes:
              type: 'sequence'
              label: 'The layout classes'
              sequence:
                - type: string
                  label: 'Field class'
            wrappers:
              type: 'sequence'
              label: 'The layout wrappers'
              sequence:
                - type: string
                  label: 'Field wrapper'
            outer_wrapper:
              type: string
              label: 'The outer wrapper of the layout'
            attributes:
              type: string
              label: 'The attributesof the layout'
            link_attribute:
              type: string
              label: 'The link attribute of the layout'
            link_custom:
              type: string
              label: 'The custom path of the layout'
    regions:
      type: sequence
      label: 'The regions of the layout'
      sequence:
        - type: sequence
          label: 'The fields belonging to the region'
          sequence:
            - type: string
              label: 'The field name'

field.formatter.third_party.ds:
  type: mapping
  label:  Display Suite field formatter settings
  mapping:
    ft:
      type: mapping
      label: 'The field template of the field'
      mapping:
        id:
          type: string
          label: 'The ID of the template'
        settings:
          ds.field_template.[%parent.id]
